# Generated by Django 3.0.3 on 2020-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.CharField(choices=[('bad', -1), ('excellent', 1), ('average', 0)], default='average', max_length=50)),
            ],
        ),
    ]
